services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --drafts --watch --force_polling --livereload -H 0.0.0.0
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - '8888:4000'
      - '35729:35729'
    environment:
      JEKYLL_ENV: development

